services:
  api:
    container_name: api
    build: .
    ports:
      - "3000:3000"
    env_file: .env
    restart: always
    networks:
      - web-network

networks:
  web-network:
    external: true
